module.exports = {
    SUCCESS: "Success",
    USER_ALREADY_EXISTS: "Email/UserName Already Exists",
    USER_LOGIN_SUCCESS: "Logged In Successfully",
    USER_REGISTER_SUCCESS: "User Registered Successfully",
    ADMIN_VERIFICATION_PENDING: "Email/UserName Exists, Admin Verification Pending",
    BAD_CREDENTAILS: "Email/Password not matched",
    PASSWORD_CONFIRMPASSWORD:"Password and Confirmed Password does not match",
    SOMETHING_ERROR_OCCURRED: "Something Error Occurred",
    USER_DOESNOT_EXISTS: "User Does Not Exists",
    JWT_SIGN_ERROR: "Error while signing JWT Error",
    SESSION_ALREADY_EXISTS: "Session Already Exists, Please Logout",
    OTP_SENT_SUCCESSFULLY: "OTP Sent to Email Successfully",
    OTP_VERIFIED_SUCCESSFULLY: "OTP Verification Successfull",
    OTP_INVALID: "OTP is Invalid/Expired",
    OTP_EXISTS: "OTP ALREADY SENT. Please Verify/Resend after sometime",
    EMAIL_SENT_SUCCESSFULLY: "Email Sent Successsfully",
    RESET_LINK_EXISTS: "Reset Link Already Exists. Please Reset/Resend after sometime",
    USER_ALEADY_VERIFIED: "User Already Verified",
    EMAIL_VERIFICATION_SUCCESS: "Email Verified Successfully",
    INVALID_RESET_LINK: "Reset Link Invalid Or Expired",
    PASSWORD_UPDATED: "Password Updated Successfully. Please login",
    SESSION_EXPIRED: "Session TimeOut/Expired. Please login again",
    TOKEN_EXPIRED:"Token Expired",
    UNAUTHORIZED_ACCESS: "Token Invalid/Unauthorized Access",
    EMAIL_TAKEN: "Email Already Taken",
    USERNAME_TAKEN: "User Name already Taken",
    USER_LOGGED_OUT_SUCCESS:"User Logged Out Successfully",
    SESSION_DOESNOT_EXISTS: "Session Not Found"
}